/**
 * zh.wikipedia-mined family data — supplements Wikidata with richer kinship
 * information extracted from article prose (家庭/家世/家族 sections).
 *
 * Data files are generated by scripts/fetch-zhwiki-family-batch.ts then
 * scripts/import-zhwiki-families.ts. They are STATICALLY imported (not read at
 * runtime) so Next.js bundles them into the serverless functions on Vercel —
 * runtime readdir/readFile of these paths is not traced and fails in prod.
 *
 * Admin keys carry a `zhwiki:` prefix so resolveSource tells them apart from
 * the Wikidata sources that share the same base key.
 */
import type { GenealogyDataset, GenealogySource } from "../types";
import zh_bai_chongxi from "./bai_chongxi.zhwiki.data.json";
import zh_baijuyi from "./baijuyi.zhwiki.data.json";
import zh_bingxin from "./bingxin.zhwiki.data.json";
import zh_cai_hesen from "./cai_hesen.zhwiki.data.json";
import zh_caijing from "./caijing.zhwiki.data.json";
import zh_caixiang from "./caixiang.zhwiki.data.json";
import zh_caiyong from "./caiyong.zhwiki.data.json";
import zh_caiyuanpei from "./caiyuanpei.zhwiki.data.json";
import zh_caoyu from "./caoyu.zhwiki.data.json";
import zh_chenbaozhen from "./chenbaozhen.zhwiki.data.json";
import zh_chenduxiu from "./chenduxiu.zhwiki.data.json";
import zh_chengyi from "./chengyi.zhwiki.data.json";
import zh_chenjiageng from "./chenjiageng.zhwiki.data.json";
import zh_chenqimei from "./chenqimei.zhwiki.data.json";
import zh_chenyinke from "./chenyinke.zhwiki.data.json";
import zh_chiang from "./chiang.zhwiki.data.json";
import zh_chusuiliang from "./chusuiliang.zhwiki.data.json";
import zh_dengjiaxian from "./dengjiaxian.zhwiki.data.json";
import zh_dumu from "./dumu.zhwiki.data.json";
import zh_fangbao from "./fangbao.zhwiki.data.json";
import zh_fangxuanling from "./fangxuanling.zhwiki.data.json";
import zh_fanwencheng from "./fanwencheng.zhwiki.data.json";
import zh_fanzhongyan from "./fanzhongyan.zhwiki.data.json";
import zh_fengyoulan from "./fengyoulan.zhwiki.data.json";
import zh_fengyuxiang from "./fengyuxiang.zhwiki.data.json";
import zh_fubi from "./fubi.zhwiki.data.json";
import zh_gongzizhen from "./gongzizhen.zhwiki.data.json";
import zh_guomoruo from "./guomoruo.zhwiki.data.json";
import zh_guweijun from "./guweijun.zhwiki.data.json";
import zh_guxiancheng from "./guxiancheng.zhwiki.data.json";
import zh_guxianrong from "./guxianrong.zhwiki.data.json";
import zh_hanshizhong from "./hanshizhong.zhwiki.data.json";
import zh_hanyi from "./hanyi.zhwiki.data.json";
import zh_hanyu from "./hanyu.zhwiki.data.json";
import zh_hedong from "./hedong.zhwiki.data.json";
import zh_huangxing from "./huangxing.zhwiki.data.json";
import zh_huangyanpei from "./huangyanpei.zhwiki.data.json";
import zh_huangzongxi from "./huangzongxi.zhwiki.data.json";
import zh_hushi from "./hushi.zhwiki.data.json";
import zh_jiyun from "./jiyun.zhwiki.data.json";
import zh_kangyouwei from "./kangyouwei.zhwiki.data.json";
import zh_kongzi from "./kongzi.zhwiki.data.json";
import zh_kouzhun from "./kouzhun.zhwiki.data.json";
import zh_laoshe from "./laoshe.zhwiki.data.json";
import zh_li_shangyin from "./li_shangyin.zhwiki.data.json";
import zh_lianheng from "./lianheng.zhwiki.data.json";
import zh_liaozhongkai from "./liaozhongkai.zhwiki.data.json";
import zh_lideyu from "./lideyu.zhwiki.data.json";
import zh_lidongyang from "./lidongyang.zhwiki.data.json";
import zh_lihongzhang from "./lihongzhang.zhwiki.data.json";
import zh_linzexu from "./linzexu.zhwiki.data.json";
import zh_lisiguang from "./lisiguang.zhwiki.data.json";
import zh_liuji from "./liuji.zhwiki.data.json";
import zh_liuzongyuan from "./liuzongyuan.zhwiki.data.json";
import zh_luyou from "./luyou.zhwiki.data.json";
import zh_lvmengzheng from "./lvmengzheng.zhwiki.data.json";
import zh_mei from "./mei.zhwiki.data.json";
import zh_nalan from "./nalan.zhwiki.data.json";
import zh_ouyang_xun from "./ouyang_xun.zhwiki.data.json";
import zh_peidu from "./peidu.zhwiki.data.json";
import zh_qian from "./qian.zhwiki.data.json";
import zh_qiandaxin from "./qiandaxin.zhwiki.data.json";
import zh_qianqianyi from "./qianqianyi.zhwiki.data.json";
import zh_qianxuantong from "./qianxuantong.zhwiki.data.json";
import zh_qibaishi from "./qibaishi.zhwiki.data.json";
import zh_rong from "./rong.zhwiki.data.json";
import zh_ruanyuan from "./ruanyuan.zhwiki.data.json";
import zh_simaguang from "./simaguang.zhwiki.data.json";
import zh_simaqian from "./simaqian.zhwiki.data.json";
import zh_songjing from "./songjing.zhwiki.data.json";
import zh_songyingxing from "./songyingxing.zhwiki.data.json";
import zh_soong from "./soong.zhwiki.data.json";
import zh_sushi from "./sushi.zhwiki.data.json";
import zh_tangshaoyi from "./tangshaoyi.zhwiki.data.json";
import zh_tangxianzu from "./tangxianzu.zhwiki.data.json";
import zh_tanyankai from "./tanyankai.zhwiki.data.json";
import zh_taoyuanming from "./taoyuanming.zhwiki.data.json";
import zh_tian_han from "./tian_han.zhwiki.data.json";
import zh_wanganshi from "./wanganshi.zhwiki.data.json";
import zh_wangniansun from "./wangniansun.zhwiki.data.json";
import zh_wangshizhen from "./wangshizhen.zhwiki.data.json";
import zh_wangshizhen2 from "./wangshizhen2.zhwiki.data.json";
import zh_wangwei from "./wangwei.zhwiki.data.json";
import zh_wangxijue from "./wangxijue.zhwiki.data.json";
import zh_wangxizhi from "./wangxizhi.zhwiki.data.json";
import zh_weiyingwu from "./weiyingwu.zhwiki.data.json";
import zh_weizheng from "./weizheng.zhwiki.data.json";
import zh_wen_yiduo from "./wen_yiduo.zhwiki.data.json";
import zh_wengtonghe from "./wengtonghe.zhwiki.data.json";
import zh_wengwenhao from "./wengwenhao.zhwiki.data.json";
import zh_wentianxiang from "./wentianxiang.zhwiki.data.json";
import zh_wenyanbo from "./wenyanbo.zhwiki.data.json";
import zh_xiean from "./xiean.zhwiki.data.json";
import zh_xiejin from "./xiejin.zhwiki.data.json";
import zh_xu_zhimo from "./xu_zhimo.zhwiki.data.json";
import zh_xubeihong from "./xubeihong.zhwiki.data.json";
import zh_xujie from "./xujie.zhwiki.data.json";
import zh_yanfu from "./yanfu.zhwiki.data.json";
import zh_yangwanli from "./yangwanli.zhwiki.data.json";
import zh_yansong from "./yansong.zhwiki.data.json";
import zh_yanxiu from "./yanxiu.zhwiki.data.json";
import zh_yanzhenqing from "./yanzhenqing.zhwiki.data.json";
import zh_yaochong from "./yaochong.zhwiki.data.json";
import zh_yeluchucai from "./yeluchucai.zhwiki.data.json";
import zh_yexianggao from "./yexianggao.zhwiki.data.json";
import zh_yuan from "./yuan.zhwiki.data.json";
import zh_yuanmei from "./yuanmei.zhwiki.data.json";
import zh_yuanzhen from "./yuanzhen.zhwiki.data.json";
import zh_yuefei from "./yuefei.zhwiki.data.json";
import zh_yuxin from "./yuxin.zhwiki.data.json";
import zh_zenggong from "./zenggong.zhwiki.data.json";
import zh_zhangjiasen from "./zhangjiasen.zhwiki.data.json";
import zh_zhangjiuling from "./zhangjiuling.zhwiki.data.json";
import zh_zhangjuzheng from "./zhangjuzheng.zhwiki.data.json";
import zh_zhangtaiyan from "./zhangtaiyan.zhwiki.data.json";
import zh_zhangying from "./zhangying.zhwiki.data.json";
import zh_zhangyue from "./zhangyue.zhwiki.data.json";
import zh_zhangzhidong from "./zhangzhidong.zhwiki.data.json";
import zh_zhangzuolin from "./zhangzuolin.zhwiki.data.json";
import zh_zhaomengfu from "./zhaomengfu.zhwiki.data.json";
import zh_zhaoyuanren from "./zhaoyuanren.zhwiki.data.json";
import zh_zhengchenggong from "./zhengchenggong.zhwiki.data.json";
import zh_zhengxuan from "./zhengxuan.zhwiki.data.json";
import zh_zhoupeiyuan from "./zhoupeiyuan.zhwiki.data.json";
import zh_zhouxuexi from "./zhouxuexi.zhwiki.data.json";
import zh_zhugeliang from "./zhugeliang.zhwiki.data.json";
import zh_zhuxi from "./zhuxi.zhwiki.data.json";
import zh_zuozongtang from "./zuozongtang.zhwiki.data.json";

const DATASETS = new Map<string, GenealogyDataset>([
  ["bai_chongxi", zh_bai_chongxi as GenealogyDataset],
  ["baijuyi", zh_baijuyi as GenealogyDataset],
  ["bingxin", zh_bingxin as GenealogyDataset],
  ["cai_hesen", zh_cai_hesen as GenealogyDataset],
  ["caijing", zh_caijing as GenealogyDataset],
  ["caixiang", zh_caixiang as GenealogyDataset],
  ["caiyong", zh_caiyong as GenealogyDataset],
  ["caiyuanpei", zh_caiyuanpei as GenealogyDataset],
  ["caoyu", zh_caoyu as GenealogyDataset],
  ["chenbaozhen", zh_chenbaozhen as GenealogyDataset],
  ["chenduxiu", zh_chenduxiu as GenealogyDataset],
  ["chengyi", zh_chengyi as GenealogyDataset],
  ["chenjiageng", zh_chenjiageng as GenealogyDataset],
  ["chenqimei", zh_chenqimei as GenealogyDataset],
  ["chenyinke", zh_chenyinke as GenealogyDataset],
  ["chiang", zh_chiang as GenealogyDataset],
  ["chusuiliang", zh_chusuiliang as GenealogyDataset],
  ["dengjiaxian", zh_dengjiaxian as GenealogyDataset],
  ["dumu", zh_dumu as GenealogyDataset],
  ["fangbao", zh_fangbao as GenealogyDataset],
  ["fangxuanling", zh_fangxuanling as GenealogyDataset],
  ["fanwencheng", zh_fanwencheng as GenealogyDataset],
  ["fanzhongyan", zh_fanzhongyan as GenealogyDataset],
  ["fengyoulan", zh_fengyoulan as GenealogyDataset],
  ["fengyuxiang", zh_fengyuxiang as GenealogyDataset],
  ["fubi", zh_fubi as GenealogyDataset],
  ["gongzizhen", zh_gongzizhen as GenealogyDataset],
  ["guomoruo", zh_guomoruo as GenealogyDataset],
  ["guweijun", zh_guweijun as GenealogyDataset],
  ["guxiancheng", zh_guxiancheng as GenealogyDataset],
  ["guxianrong", zh_guxianrong as GenealogyDataset],
  ["hanshizhong", zh_hanshizhong as GenealogyDataset],
  ["hanyi", zh_hanyi as GenealogyDataset],
  ["hanyu", zh_hanyu as GenealogyDataset],
  ["hedong", zh_hedong as GenealogyDataset],
  ["huangxing", zh_huangxing as GenealogyDataset],
  ["huangyanpei", zh_huangyanpei as GenealogyDataset],
  ["huangzongxi", zh_huangzongxi as GenealogyDataset],
  ["hushi", zh_hushi as GenealogyDataset],
  ["jiyun", zh_jiyun as GenealogyDataset],
  ["kangyouwei", zh_kangyouwei as GenealogyDataset],
  ["kongzi", zh_kongzi as GenealogyDataset],
  ["kouzhun", zh_kouzhun as GenealogyDataset],
  ["laoshe", zh_laoshe as GenealogyDataset],
  ["li_shangyin", zh_li_shangyin as GenealogyDataset],
  ["lianheng", zh_lianheng as GenealogyDataset],
  ["liaozhongkai", zh_liaozhongkai as GenealogyDataset],
  ["lideyu", zh_lideyu as GenealogyDataset],
  ["lidongyang", zh_lidongyang as GenealogyDataset],
  ["lihongzhang", zh_lihongzhang as GenealogyDataset],
  ["linzexu", zh_linzexu as GenealogyDataset],
  ["lisiguang", zh_lisiguang as GenealogyDataset],
  ["liuji", zh_liuji as GenealogyDataset],
  ["liuzongyuan", zh_liuzongyuan as GenealogyDataset],
  ["luyou", zh_luyou as GenealogyDataset],
  ["lvmengzheng", zh_lvmengzheng as GenealogyDataset],
  ["mei", zh_mei as GenealogyDataset],
  ["nalan", zh_nalan as GenealogyDataset],
  ["ouyang_xun", zh_ouyang_xun as GenealogyDataset],
  ["peidu", zh_peidu as GenealogyDataset],
  ["qian", zh_qian as GenealogyDataset],
  ["qiandaxin", zh_qiandaxin as GenealogyDataset],
  ["qianqianyi", zh_qianqianyi as GenealogyDataset],
  ["qianxuantong", zh_qianxuantong as GenealogyDataset],
  ["qibaishi", zh_qibaishi as GenealogyDataset],
  ["rong", zh_rong as GenealogyDataset],
  ["ruanyuan", zh_ruanyuan as GenealogyDataset],
  ["simaguang", zh_simaguang as GenealogyDataset],
  ["simaqian", zh_simaqian as GenealogyDataset],
  ["songjing", zh_songjing as GenealogyDataset],
  ["songyingxing", zh_songyingxing as GenealogyDataset],
  ["soong", zh_soong as GenealogyDataset],
  ["sushi", zh_sushi as GenealogyDataset],
  ["tangshaoyi", zh_tangshaoyi as GenealogyDataset],
  ["tangxianzu", zh_tangxianzu as GenealogyDataset],
  ["tanyankai", zh_tanyankai as GenealogyDataset],
  ["taoyuanming", zh_taoyuanming as GenealogyDataset],
  ["tian_han", zh_tian_han as GenealogyDataset],
  ["wanganshi", zh_wanganshi as GenealogyDataset],
  ["wangniansun", zh_wangniansun as GenealogyDataset],
  ["wangshizhen", zh_wangshizhen as GenealogyDataset],
  ["wangshizhen2", zh_wangshizhen2 as GenealogyDataset],
  ["wangwei", zh_wangwei as GenealogyDataset],
  ["wangxijue", zh_wangxijue as GenealogyDataset],
  ["wangxizhi", zh_wangxizhi as GenealogyDataset],
  ["weiyingwu", zh_weiyingwu as GenealogyDataset],
  ["weizheng", zh_weizheng as GenealogyDataset],
  ["wen_yiduo", zh_wen_yiduo as GenealogyDataset],
  ["wengtonghe", zh_wengtonghe as GenealogyDataset],
  ["wengwenhao", zh_wengwenhao as GenealogyDataset],
  ["wentianxiang", zh_wentianxiang as GenealogyDataset],
  ["wenyanbo", zh_wenyanbo as GenealogyDataset],
  ["xiean", zh_xiean as GenealogyDataset],
  ["xiejin", zh_xiejin as GenealogyDataset],
  ["xu_zhimo", zh_xu_zhimo as GenealogyDataset],
  ["xubeihong", zh_xubeihong as GenealogyDataset],
  ["xujie", zh_xujie as GenealogyDataset],
  ["yanfu", zh_yanfu as GenealogyDataset],
  ["yangwanli", zh_yangwanli as GenealogyDataset],
  ["yansong", zh_yansong as GenealogyDataset],
  ["yanxiu", zh_yanxiu as GenealogyDataset],
  ["yanzhenqing", zh_yanzhenqing as GenealogyDataset],
  ["yaochong", zh_yaochong as GenealogyDataset],
  ["yeluchucai", zh_yeluchucai as GenealogyDataset],
  ["yexianggao", zh_yexianggao as GenealogyDataset],
  ["yuan", zh_yuan as GenealogyDataset],
  ["yuanmei", zh_yuanmei as GenealogyDataset],
  ["yuanzhen", zh_yuanzhen as GenealogyDataset],
  ["yuefei", zh_yuefei as GenealogyDataset],
  ["yuxin", zh_yuxin as GenealogyDataset],
  ["zenggong", zh_zenggong as GenealogyDataset],
  ["zhangjiasen", zh_zhangjiasen as GenealogyDataset],
  ["zhangjiuling", zh_zhangjiuling as GenealogyDataset],
  ["zhangjuzheng", zh_zhangjuzheng as GenealogyDataset],
  ["zhangtaiyan", zh_zhangtaiyan as GenealogyDataset],
  ["zhangying", zh_zhangying as GenealogyDataset],
  ["zhangyue", zh_zhangyue as GenealogyDataset],
  ["zhangzhidong", zh_zhangzhidong as GenealogyDataset],
  ["zhangzuolin", zh_zhangzuolin as GenealogyDataset],
  ["zhaomengfu", zh_zhaomengfu as GenealogyDataset],
  ["zhaoyuanren", zh_zhaoyuanren as GenealogyDataset],
  ["zhengchenggong", zh_zhengchenggong as GenealogyDataset],
  ["zhengxuan", zh_zhengxuan as GenealogyDataset],
  ["zhoupeiyuan", zh_zhoupeiyuan as GenealogyDataset],
  ["zhouxuexi", zh_zhouxuexi as GenealogyDataset],
  ["zhugeliang", zh_zhugeliang as GenealogyDataset],
  ["zhuxi", zh_zhuxi as GenealogyDataset],
  ["zuozongtang", zh_zuozongtang as GenealogyDataset],
]);

export type ZhwikiFamilyMeta = {
  key: string;
  label: string;
  people: number;
  deceased: number;
  photos: number;
};

export const zhwikiFamilyList: ZhwikiFamilyMeta[] = [...DATASETS.entries()]
  .map(([key, ds]) => ({
    key: `zhwiki:${key}`,
    label: `${ds.people[0]?.name ?? key}（维基百科补充·${ds.people.length}人）`,
    people: ds.people.length,
    deceased: ds.people.filter((p) => !p.living).length,
    photos: 0,
  }))
  .sort((a, b) => b.people - a.people);

/** A source for one zhwiki family (prefixed key), or undefined if unknown. */
export function zhwikiFamilySource(prefixedKey: string): GenealogySource | undefined {
  if (!prefixedKey.startsWith("zhwiki:")) return undefined;
  const baseKey = prefixedKey.slice("zhwiki:".length);
  const dataset = DATASETS.get(baseKey);
  if (!dataset) return undefined;
  return { key: dataset.key, load: async () => dataset };
}

export function zhwikiImportedCounts(
  importedIds: Set<string>,
): Record<string, number> {
  const out: Record<string, number> = {};
  for (const [key, ds] of DATASETS) {
    out[`zhwiki:${key}`] = ds.people.filter(
      (p) => !p.living && importedIds.has(p.externalId),
    ).length;
  }
  return out;
}
